### ISSUE TITLE
Readme update for check for the MSIE user agent

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/usefulJquery#24]
Need to add check for the MSIE user agent to the readme

**Comment by owenvoke** [comment]
Will add this. :smile

**Comment by owenvoke** [comment]
Nice job @yongzhihuang

**Comment by owenvoke** [comment]
@RogerCreasy Should this be marked as Closed? 😄

**Comment by RogerCreasy** [comment]
Yep. Closing. 
(sorry for being slow) crazy couple of days at work)
