### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/usefulJquery#8]
I am looking for someone (or multiple someones) to create a directory of snippets in the readme. If you are willing to create a summary for one or more of the snippets, please submit a PR.

Again, an easy PR for Hactoberfest.

**Comment by owenvoke** [comment]
What do you mean? 😄 Are these snippets meant to be like, the HTML that is needed? Or just the element with the class? i.e. `<div class="backToTop"></div>`

Or is it a list of the different things that are included?

**Comment by chrisonntag** [comment]
Or a combination of both? 😉
We could write a short description of each snippet and how to use it.

**Comment by owenvoke** [comment]
Sounds good 😄 I'll have a go 👍

**Comment by oylenshpeegul** [comment]
Oops, I just added the descriptions from the code.

**Comment by owenvoke** [comment]
I added a pull request (it doesn't cover all of them, but I'll add them later, I just wanted to give an example and see what you think).
Demo: https://github.com/PXgamer/usefulJquery
PR: #10

**Comment by kartik95** [comment]
What kind of snippets are we talking about here?

**Comment by owenvoke** [comment]
@kartik95 he answered a little bit further up. (kinda) 😄 

HTML and examples, with a description.

**Comment by kartik95** [comment]
Yeah got them. Thanks. :smile: 
Also, are these general snippets found on the internet? Or are they self made?

**Comment by owenvoke** [comment]
I think they're meant to be self made (using the scripts that are in this repo)

**Comment by kartik95** [comment]
Okay, thanks. I'll get on to it then. :)

**Comment by owenvoke** [comment]
I've now added descriptions and snippets for all of the `js` files currently in here to #10.
